### ISSUE TITLE
Create Portal-specific About page

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#106]
Can we keep the Portal menu in the header on the About page, as well? A Phase 1 user reported: "After navigating to the "about" page, the menu selection disappears, so you can only leave the page with the browser's back button"

**Comment by EmilyHaag** [comment]
Phase 1 feedback from Meg: Create a Portal-specific About page

**Comment by candicecz** [comment]
About page is created, pending more feedback on content. Will close for now.
