### ISSUE TITLE
Add `species` scientific and common name to filters

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#112]
Following concept normalization of `species` and `infectiousAgent` (https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/90), add both the scientific and common names of the species to the filters. Maybe something like:
<img width="370" alt="Screen Shot 2022-10-27 at 4 01 59 PM" src="https://user-images.githubusercontent.com/8041065/198414027-7c1f71d9-05c6-4f24-b721-541e1a20db91.png">

**Comment by candicecz** [comment]
Viewable in the [dev instance](https://d3d1vy3voytpzm.cloudfront.net/resources?id=GEO_GSE87546) 
Dataset :
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/25373313/751dd76b-4f98-4a8c-9864-13dd4410a875)
Search filters:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/25373313/f0c40934-5114-4a79-816a-3e06467a658f)

**Comment by gtsueng** [comment]
This issue was mentioned in a digest email dated 2023.12.14

**Comment by gtsueng** [comment]
The ask: This view is now available on staging and made possible by the metadata improvements currently on staging. We would like to move this to production.

**Comment by gtsueng** [comment]
The ask: This view is now available on staging and made possible by the metadata improvements currently on staging. We would like to move this to production.

We have elevated the priority of this issue as the back end metadata improvements that enable this feature have been approved for production. Further, other UI improvements on staging have also been approved for Production and it would be more efficient to move these changes together than to revert this one and move the others forward.

**Comment by hartwickma** [comment]
Thank you for this update. OK to move to production and provide an update of the impact and outcomes of this update in an upcoming bi-weekly meeting.

Please note: Please consider developing an approach that makes it clear when issues are inter-dependancies between or issues that have substantial overlap in order to improve the efficiency of the approval process. (eg: action for issue #110 (pubtator) required further action be approved for #90 and #112, action for #104, #102 and #215 were also interdependant).

**Comment by gtsueng** [comment]
We will investigate ways to improve ease with which related tickets can be viewed in the project board. Per @rshabman's comment on the ticket about the project board, we will document these requests (requests about PM tracking) in a google doc.

That said, We have updated the status of this ticket to `Pending close out` on 2024.01.18. If there are no objections by 2024.01.25, we will proceed to close this issue.

**Comment by hartwickma** [comment]
>If there are no technical reasons to delay close out, please close this issue.

**Comment by gtsueng** [comment]
Understood
