### ISSUE TITLE
[UX] Advanced search - Show all options in the dropdown menu unless the user has selected a value

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#118]
If I've selected a value within the query builder, if I go back to the dropdown menu, I can only see that value within the list. 
<img width="349" alt="Screenshot 2022-12-06 at 4 37 15 PM" src="https://user-images.githubusercontent.com/8041065/206058349-079434b2-f9e2-47f6-932a-910110a8056d.png">

As a user, I find that confusing -- I would have expected the dropdown list to contain _all_ fields, not the one I selected. Part of the confusion may be related to the dropdown menu being mixed with the search within the list functionality (see #117).  I would expect that behavior if I had typed "pathogen" within the search box, but since I selected from the list, it feels weird.  It might be clearer if the dropdown menu was separate from the internal search bar, so you could have a "clear search" button.

**Comment by EmilyHaag** [comment]
I also had trouble using this until I realized the dropdown also operates like a textbox but this took me a while to figure out.
