### ISSUE TITLE
[UX] Advanced query searching is case sensitive

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#123]
`healthCondition:HIV` works, but `healthCondition:hiv` does not.  I would expect these queries to be case insensitive.

**Comment by andrewsu** [comment]
I think this is related (if not, let me know and I can create a new ticket), but on https://data-staging.niaid.nih.gov/portal/search/?q=%22Influenza%22+OR+%22Flu%22, I see separate values for `influenza` and `Influenza` in the "Health Condition" facet section.

![image](https://user-images.githubusercontent.com/2635409/208774130-ebfdfe2d-0ac8-4474-ad21-1ed9f3747c4c.png)

**Comment by flaneuse** [comment]
@andrewsu we're planning on dealing with the case sensitivity by running all the healthCondition values through PubTator to standardize all these values to MeSH terms.  If you have better ideas about how to do this normalization, please suggest!

**Comment by andrewsu** [comment]
That seems like a great idea and better than what I was envisioning!

**Comment by flaneuse** [comment]
yeah, you can fix it on the front-end, which could be a good temporary fix, but you'd have to recompute after the elasticsearch aggregation, so felt like we should just fix the data.
