### ISSUE TITLE
Examples or more context for specific fields

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#130]
The hover-over descriptions for the fields within the advanced search module are excellent. It may also be useful to provide some context around how to use that field after it's been selected - at least for certain fields, for example, aggregate rating count. Is this a string or an integer? Maybe when certain fields are selected, the search box could give example queries.

And if some fields are integers, maybe "greater than" and "less than" should be added to the query builder options (in the list, like "contains")?

**Comment by flaneuse** [comment]
i've always loved the data type icons [Trifacta](https://www.trifacta.com/) uses to indicate type:

![image](https://user-images.githubusercontent.com/8041065/207177657-c32f5c97-fdf4-409b-8d27-3341c9832ac1.png)

I think Tableau and others use similar -- not sure who deserves credit for starting it off.

**Comment by EmilyHaag** [comment]
Additional feedback from internal tester: "it was difficult to understand the individual fields (what are they? what kind of values are the options here?)"

**Comment by candicecz** [comment]
Added inputs based on metadata field type + added icons to suggest the field type to dropdown.
