### ISSUE TITLE
Drop search bar from /sources?

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#132]
Is it confusing to have a search bar on `/sources`? I was looking at it today, thinking it would be used to search within the data sources, not the datasets/tools themselves.  thoughts?
<img width="1713" alt="Screenshot 2022-12-12 at 6 13 41 PM" src="https://user-images.githubusercontent.com/8041065/207209590-2c1d6436-2c6c-4299-99cf-faa4d1e21fb6.png">

**Comment by candicecz** [comment]
Removed dataset search and added a search input for sources.
