### ISSUE TITLE
[Discussion] Highlight Keywords and Description more on resource details page?

### ISSUE THREAD

**Issue by andrewsu** [NIAID-Data-Ecosystem/nde-portal#147]
For discussion/consideration....  Right now, there are sections for Overview, Keywords, Description, Provenance, Funding, and Metadata. Would it be worth considering pulling out the Keywords and Description to be a more integrated part of the page (under the resource title, perhaps)? I think this _could_ bring information higher that would be useful to the user at first glance.

**Comment by gtsueng** [comment]
The coverage of `description` is generally very high >90%, but I'm not sure about the coverage of `keywords`. @leandrocollares can you check the coverage of the `keywords` field currently on production? This will let us know how much impact this UI improvement might have.

**Comment by gtsueng** [comment]
Keyword coverage is here: https://docs.google.com/presentation/d/173iq49N4FRulkf7R-s-L3defEDY2hjEzxnQvBQKo7Kk/edit#slide=id.g2f10e6bde1c_0_158

@DylanWelzel to provide a dump of `description` for @leandrocollares to analyze. Description length will play an important role in determining whether or not ChatGPT can be used to generate a short description of the Dataset. (It tends to over hallucinate for topicCategory and measurementTechnique) when the name+description of a dataset is too short
