### ISSUE TITLE
Remove "contains" for date/numeric searching in advanced search?

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#151]
In the advanced search module, when searching for a date, the resulting box in the query builder shows it as being "contains".  It feels like for date and numeric searches, these labels don't make sense -- so maybe remove the radio button for contains/exact/etc. from those fields, and the labels from the query builder drag and drop?

<img width="1100" alt="Screenshot 2023-01-05 at 4 08 20 PM" src="https://user-images.githubusercontent.com/8041065/210903822-da62585f-643c-4a12-b085-5ad5e3e5fcd4.png">

**Comment by candicecz** [comment]
We need some type of default option for the user to select when they toggle between "field exists" and "not exists". So for now, I've set the default option as "Field Contains" and removed the dropdown options (exacts, starts with, etc) for those fields.

I've removed the "contains" text on the tags for those fields too.
