### ISSUE TITLE
Exact match autocomplete preview: should this be a "contains" search?

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#153]
I'm wondering whether the autocomplete previews for "exact matching" should show the results from a contains search. For instance, if I'm searching for NIAID, I think I would expect to see `NIAID NIH HHS`, `National Institute of Allergy and Infectious Diseases (NIAID)`, `NIAID`, etc., so i could choose which one of those I would want to exact match.

<img width="1100" alt="Screenshot 2023-01-05 at 4 34 32 PM" src="https://user-images.githubusercontent.com/8041065/210905920-70f7b791-999a-4e21-9769-7f9cecee1364.png">

Thoughts @candicecz @EmilyHaag ?

**Comment by candicecz** [comment]
Changing it to options to "contains" makes sense to me as well, we can see what user feedback we get in the long run...
Let me know if I should go ahead and make the change.
