### ISSUE TITLE
Advanced Search breaks after adding 2nd field

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#161]
At the moment, if the user adds one search term (e.g. "Type: Dataset", AND), then clicks another field to continue adding to the query, it returns an application error (see screenshot). This was not happening last week.

![Screenshot (741)](https://user-images.githubusercontent.com/75391907/215609248-1f843153-68a4-40f0-abd8-15a7f8b7c3e2.png)

**Comment by flaneuse** [comment]
error: `TypeError: Cannot read properties of undefined (reading 'name')`

Looks like this isn't a problem with combining general queries but is an issue if you try to combine two fielded queries.
