### ISSUE TITLE
Add nav bar to 404 page

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#175]
On a random page (https://data-staging.niaid.nih.gov/fjdsklaf), the 404 page has the footer but is missing the header, which would be useful for going backward to a working page.

https://data-staging.niaid.nih.gov/404 also redirects to https://data-staging.niaid.nih.gov/staging/404/ for some reason.

**Comment by DylanWelzel** [comment]
fixed nav on 404 with #178, redirect still issue

**Comment by flaneuse** [comment]
@DylanWelzel just realized this redirect is because there's no trailing `/` on the end of the URL.  it's something @candicecz has been trying to fix for awhile with no luck. We should revisit this when y'all have time, since the routing should be much simpler now and there's no need for `/staging` to exist (I think).
