### ISSUE TITLE
Change "Dataverse" to "Harvard Dataverse" on front end

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#194]
This was a request from folks working on the Harvard Dataverse:

"On the Generalist Repositories list at https://data.niaid.nih.gov/ (https://data.niaid.nih.gov/), could the text Dataverse be changed to 'Harvard Dataverse'? There are multiple Dataverse repositories, and it looks like the Discovery Portal contains only datasets from Harvard's repository."

**Comment by candicecz** [comment]
@DylanWelzel  can you change it in the metadata?

**Comment by DylanWelzel** [comment]
Change is live on https://data.niaid.nih.gov/
