### ISSUE TITLE
Add "exists" checkbox feature from Advanced Search to current filters

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#199]
Currently, the users can filter for specific `infectiousAgent`, `species`, `healthCondition`, etc. and the majority of these will be `Not specified` as they are missing.

It would be useful to filter for ones that have a value, regardless of what the value is. You can do this in the advanced query by selecting the field and checking the `exists` box. The NIAID team would like to have this option for each of the already available filters.

Related WBS tasks:
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52

**Comment by candicecz** [comment]
Ready for review in the [staging](https://data-staging.niaid.nih.gov/search?q=%22HIV%22+OR+%22AIDS%22)

**Comment by gtsueng** [comment]
excellent

**Comment by candicecz** [comment]
Viewable in the [production ](https://data.niaid.nih.gov/search) instance

**Comment by gtsueng** [comment]
No comment from NIAID team on this after a week in production -- we're good to close it
