### ISSUE TITLE
Make it easier for user to find pertinent information before executing query

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#2]
Suggestion from @candicecz : before actually execute the query, is there a way to help the user narrow down the results BEFORE actually going to the search page?

Thinking aloud: 
* incorporating Google-esque predictive text searching?
* displaying some sort of summary stats as you type (number of results, dataset source, ...?)
* ...

**Comment by EmilyHaag** [comment]
Adding to the brainstorm, Twitter provides a search+filter feature so you can narrow results before going to the results page:

![Screenshot (682)](https://user-images.githubusercontent.com/75391907/183989739-02bb38c5-a9b2-47d8-96c9-bfe68e9b37e3.png)

**Comment by EmilyHaag** [comment]
This was also the first item mentioned in the survey collected during Phase 0 testing

**Comment by flaneuse** [comment]
@EmilyHaag I think the feedback was mentioning #1 -- search by specific field, like `measurementTechnique: genomics`, not autosuggest results

**Comment by EmilyHaag** [comment]
I believe @candicecz mentioned she is already rolling this out, but a user suggested, "It would be nice to have auto complete suggestions as drop downs for datasets available in the ecosystem."
