### ISSUE TITLE
Revisit display of metadata elements

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#200]
Screenshot:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/918f8aaf-650e-47eb-9e27-6027f0b93639)

Background: While the colors are very nice, the greyed out icons appear to be just another color instead of an indicator that the value for this metadata field is empty. Consider using either single color-blind safe color or some other way (X on the icon?) to quickly indicate that a value for this metadata is available or not. Simply having it colored vs grey is not clear since grey appears to be just another color when many colors are present

Related WBS task:
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/52

**Comment by candicecz** [comment]
Cards with metadata tags are using [WCAG 2.1 accessible colors](https://drive.google.com/file/d/1YmL-OxiDHJSiqgOoI7uJiQnm4S4kWssd/view?usp=drive_link). 
Viewable on [staging](https://data-staging.niaid.nih.gov/search?q=%22Asthma%22)

**Comment by candicecz** [comment]
Viewable on [production ](https://data.niaid.nih.gov/search?q=%22Asthma%22).
