### ISSUE TITLE
corrupted CSV download of metadata

### ISSUE THREAD

**Issue by andrewsu** [NIAID-Data-Ecosystem/nde-portal#201]
From https://data-staging.niaid.nih.gov/search?q=plasmodium&from=1&filters=%28date%3A%5B%222022-08-01%22+TO+%222022-12-31%22%5D%29, I clicked the "Download metadata -> CSV" option and got this file:

[nde-results.csv](https://github.com/NIAID-Data-Ecosystem/nde-portal/files/12875321/nde-results.6.csv)

When loading it in excel (which is how most people will probably view it), you'll see there are many cases where the column parsing isn't correct. I suspect that it has to do with unescaped quotes, newline characters in cell values, or possibly exceeding maximum string lengths in excel. Needs further investigation...

(But I'll note that the `isBasedOn.additionalType.url` looks funny to me -- an example value is shown below for `NCBI_SRA_SRP387013`)

<details>
<summary>`isBasedOn.additionalType.url` for `NCBI_SRA_SRP387013`</summary>

`["http://purl.obolibrary.org/obo/NCIT_C45293","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699","http://purl.obolibrary.org/obo/NCIT_C47911","http://purl.obolibrary.org/obo/NCIT_C42790","http://purl.obolibrary.org/obo/NCIT_C70699"]`
</details>

**Comment by candicecz** [comment]
Andrew found [this dataset ](https://data.niaid.nih.gov/resources?id=NCBI_SRA_SRP385254) that specifically has the issue where the value in `isBasedOn.additionalType` exceeds the [max cell count in excel](https://support.microsoft.com/en-gb/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3) and causes the corrupt csv.

As a solution, I've truncated the cell count of all cells that exceed that limit. We should also re-evaluate how we handle `isBasedOn.additionalType`
