### ISSUE TITLE
standardize "sources" vs "repositories"

### ISSUE THREAD

**Issue by andrewsu** [NIAID-Data-Ecosystem/nde-portal#202]
"Resources -> Data repositories" goes to https://data-staging.niaid.nih.gov/sources -- I suggest standardizing on either "sources" or "repositories".

![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/2635409/89659df8-4517-48b5-9cb8-5de60c31bf78)

**Comment by gtsueng** [comment]
Good catch! That was supposed to have been standardized to sources
