### ISSUE TITLE
Add copy to clipboard floating button on metadata box

### ISSUE THREAD

**Issue by newgene** [NIAID-Data-Ecosystem/nde-portal#209]
In the metadata section of a dataset page, like [this one](https://data.niaid.nih.gov/resources?id=VIVLI_31a0311f-3e6e-41d7-92cd-10ca9d666038):

<img width="728" alt="image" src="https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/130158/c5792979-526d-402c-82db-a8a44f7f6c2b">

It would be nice to add a floating button to copy the entire metadata object to clipboard.

I will post an example below.

**Comment by newgene** [comment]
This can be an example from https://react-code-block.netlify.app/usage:

<img width="847" alt="image" src="https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/130158/1640ac93-6489-4f0a-8a7b-d0af40ee29be">

Some reusable components, like this code-block component above, might have included this feature, plus other nice-to-have features like better code styling, etc.

**Comment by newgene** [comment]
This is relatively low-priority improvement.

**Comment by gahmee** [comment]
Hello! May I have permission to work on this?

I was thinking something like this?
![Capture](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/69001161/3da1b61b-41da-4971-86d2-cc8e784777c0)

**Comment by gtsueng** [comment]
Hi @gahmee, and thank you for your interest and my apologies for the late response. I have been out of town and the issue was internally assigned to someone else. I have updated it to reflect the assignment.

**Comment by leandrocollares** [comment]
Issue addressed by PR #213.

**Comment by gtsueng** [comment]
This issue was mentioned in a digest email dated 2023.12.14

**Comment by gtsueng** [comment]
The Ask: This button is now available on staging. We seek approval to move it to production.

**Comment by gtsueng** [comment]
The Ask: This button is now available on staging. We seek approval to move it to production.

We have elevated the priority of this issue as it would be more efficient to move these changes together with other UI changes than to revert this one and move the others forward.

**Comment by hartwickma** [comment]
Thank you for this update. OK to move the 'copy button' to production. 

Please note: NIAID does not need to review UI improvements at this level.

**Comment by gtsueng** [comment]
We will proceed to move this to Production

**Comment by gtsueng** [comment]
We have updated the status of this issue to `Pending close out` on 2024.01.18. If there are no objections by 2024.01.25, we will proceed to close this issue.
