### ISSUE TITLE
[REQUESTS]: Mock up of Metadata badge in Search results view and Record page view

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#215]
### Issue Name

Mock up of Metadata badge in Search results view and Record page view

### Issue Description

With the updates to the Metadata tags and the user test results on the Metadata Completeness badge, there is concern that the changes will be too cluttered when displayed in the search results page view. To assuage these concerns, please provide mock ups of how the two changes would look together on the:
1. Search results page/view
2. A record page/view

### Issue Discussion

This mock up request was raised at the bi-weekly meeting dated 2023.12.12

### Request Type

New material (mock up, page, feature, etc.)

### Material URL

https://drive.google.com/drive/folders/1HinF7HUllce0p15aNIzmnqwPMlkkVOt_?usp=drive_link

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/19

### Related Issues
https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/5?pane=issue&itemId=46354870
https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/5?pane=issue&itemId=45872920

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [x] In progress
- [ ] Blocked
- [ ] Will not address

### Request status check list

- [X] The request has been scoped
- [x] Some immediate discussion or action on the matter was started, but additional information needed
- [x] One or more new GitHub Issues, Pull Requests, or files in Google Drive have been created to address the request
- [x] The request is awaiting approval to move to staging
- [ ] The request is awaiting approval to move to production
- [ ] The request is awaiting approval for closeout
- [ ] The request has been addressed and closeout of the issue is approved

**Comment by gtsueng** [comment]
@sudvenk, @hartwickma, @rshabman, @lisa-mml
The requested mock ups can now be found here: https://drive.google.com/drive/folders/1HinF7HUllce0p15aNIzmnqwPMlkkVOt_?usp=drive_link

The mock ups show the following conditions:
* A search result page (with or without altmetric badge)
* A record view page (with or without the altmetric badge)

### Why the option of replacing the altmetric badge?
* In our previous experience with the altmetric API, there are a limited number of identifiers which can be used to pull the badge.
  * Of those identifiers, only DOI's are expected to be useful for the dataset records. The other identifiers are for related publications (PMIDs) or Clinical Trial records (NCTIDs) which would pull the altmetric badge for the publication or clinical trial itself, not the associated dataset.
* The number of records with DOIs within the Data Ecosystem is ~347K out of ~2.8 million which are distributed as follows:
![Image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/26ef27b2-8f32-4eb7-8a42-95c3bf72a26a)
(Note, if you would like to inspect the distribution of DOIs yourself, you can use the Advanced search option in the portal to search for DOI `_exists_`.

**Comment by gtsueng** [comment]
The priority of this issue was raised to high based on an email dated 12/21/2023

**Comment by gtsueng** [comment]
The ask: 
1. Do we keep Altmetrics badges when most records will not have them?
2. Can we move the record view of the metadata completeness badge to staging?
3. Which card view of the metadata completeness badge, should we move to staging? (bar view, circular badge view)

**Comment by hartwickma** [comment]
Hi Ginger and team, thanks for providing an "ask". We see that this is part of the Agenda/Slides for Tuesday's meeting. Please see our preliminary responses below that we can discuss in more depth during the call next week. Thanks!

1.	Do we keep Altmetrics badges when most records will not have them?
•	Fine to remove Altmetric badges
2.	Can we move the record view of the metadata completeness badge to staging?
•	What view is the record view (filenaming is not clear). Please let us know how this is different from the current view? Once this is clear, we’ll quickly review and reply with our decision about staging. 
3.	Which card view of the metadata completeness badge, should we move to staging? (bar view, circular badge view)
•	Move forward with the circular badge

**Comment by gtsueng** [comment]
Thanks @hartwickma for the response. The record view are the files with 'resource' in the name. It is how a single resource record would look with the metadata completeness badge and the updated metadata tags would look. The 'card' view is how each listing of the record/resource would appear in a list of search results. When you click on one of the listings ('cards') it will take you to a resource/record, displaying the resource/record view.

**Comment by hartwickma** [comment]
Hi @Ginger, the description below: 

The files were described above as:

1. A search result page (with or without altmetric badge) with the user-tested metadata badge
2. A record view page (with or without the altmetric badge) with the user-tested metadata badge
3. A search result page (with or without the altmetric badge) with a bar version of the metadata badge

But the filenames do not correspond. NIAID should look at the files named 'card' to respond to item #2 about record views? What change is NIAID asked to respond to for the 'card' files?

**Comment by gtsueng** [comment]
Hi @hartwickma, apologies for the confusion. To clarify, the metadata badges will show up in two different views/contexts:

The 'card' view is essentially an individual listing for the search result page. (The card view is circled in the context of a search result page below)


![Image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/dae716ce-9374-400f-9751-c1f80c3c11c9)

The 'card' view mock ups show how a badge would look on the search results page.

If you click on any card in the search results page, it would take you to the record for that search result. This is the record or resource view. The mockups with 'resource in the file name illustrate how the badge will look on that page.

We are proposing to move both the metadata completeness badge to staging so that it will appear in both the search results listing (for each card) and in the record page (resource)

Here are examples of how each view looks on production:
search result view (with 10 cards displayed): https://data.niaid.nih.gov/search?q=naegleria+fowleri
A record view of one of the cards: https://data.niaid.nih.gov/resources?id=veupathdb_DS_e57644bc33

Please don't hesitate to let me know if further clarification is needed.

**Comment by gtsueng** [comment]
Sorry for not thinking to do this sooner. Here's a list of the mock ups as they correspond to the description in this issue:

1. A search result page ([with](https://drive.google.com/file/d/1aJdz30BEAxcg8xQA7H_31cEMeXqFN4MW/view?usp=drive_link) or [without](https://drive.google.com/file/d/1vYqJ2igF-2zYQdx7Tc_V4gn2l5pKLdEZ/view?usp=drive_link) altmetric badge) with the user-tested metadata badge
2. A record view page ([with](https://drive.google.com/file/d/1PO7h3kmKdvn-lnoCkioofam-Rh4WydWz/view?usp=drive_link) or [without](https://drive.google.com/file/d/1WpCWbDH8HWPfPwi06GL1Q8PwrrvdD5No/view?usp=drive_link) the altmetric badge) with the user-tested metadata badge
3. A search result page ([with](https://drive.google.com/file/d/1RoGIngCAPfPK7wvLG4n6Iwhxqzm0Km9S/view?usp=drive_link) or [without](https://drive.google.com/file/d/11_ENXG6l1PtZIDd7QANENoGvzZIb1Hs1/view?usp=drive_link) the altmetric badge) with a bar version of the metadata badge

**Comment by gtsueng** [comment]
@hartwickma @rshabman @sudvenk @lisa-mml 

Per the discussion during our bi-weekly meeting on 2024.01.09, we will move the mock ups to staging. I have changed the status of this to `in progress - on staging`. @candicecz please move the metadata tags and the circular metadata completeness badge to staging. Please use the version without the altmetric badge.

**Comment by candicecz** [comment]
The following changes have moved to staging:
- [x]  Metadata tags (with WCAG 2.1 accessible color scheme)[ in the search page results](https://data-staging.niaid.nih.gov/search?q=%22SARS-CoV-2%22+OR+%22Covid-19%22+OR+%22Wuhan+coronavirus%22+OR+%22Wuhan+pneumonia%22+OR+%222019-nCoV%22+OR+%22HCoV-19%22)
- [x]  Circular metadata completeness badges [in the search page results](https://data-staging.niaid.nih.gov/search) and [in the record view page](https://data-staging.niaid.nih.gov/resources?id=GSE111097). 
- [x] Removal of altmetric badge

**Comment by gtsueng** [comment]
2024.01.17 - We have moved this item to Staging

@hartwickma @rshabman @lisa-mml @sudavenk
The ask: We request approval to move this to production.

**Comment by hartwickma** [comment]
Thank you, OK to move the metadata completenss badge to production. Please also: 

 1. draft a 'news update' on the badge and 
 2. propose a legend to describe the badge (note, this can come after production). 

This issue has substantial overlap with #109.

**Comment by gtsueng** [comment]
Thanks @hartwickma @sudavenk @rshabman @lisa-mml

@candicecz will move this from Staging to Production and @EmilyHaag will draft a news update for the metadata completeness badge and metadata tags (icons and labels) update

**Comment by candicecz** [comment]
The metadata badges are now viewable in [production](https://data.niaid.nih.gov/). Thanks!

**Comment by gtsueng** [comment]
We have updated the status of this issue to `Pending close out` on 2024.01.18. If there are no objections by 2024.01.25, we will proceed to close this issue.

We will create new issues to address the following comments: 

> Thank you, OK to move the metadata completenss badge to production. Please also:
> 
>     1. draft a 'news update' on the badge and
> 
>     2. propose a legend to describe the badge (note, this can come after production).
>

**Comment by hartwickma** [comment]
If there are no technical reasons to delay close out, please close this issue.
