### ISSUE TITLE
[User Interface: Redesign]: Display of Resource Catalogs on search results page

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#218]
### Issue Name

Display of Resource Catalogs

### Issue Description

Five Resource Catalogs have now been ingested from the DDE. Based on previous work involving the ComputationalTools and discussions with the NIAID team, we expect the Resource Catalogs to roughly be displayed as follows:
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/53d1d600-9b51-4614-a31c-e3752e37171e)

The terminology to be used for the `subterm` is expected to be the value of the `collectionType` field

To be determined: 
- The best term for the `Term` in this image (Other? Resource Catalog? Resource? Source?)
- The color of the bar (same as Datasets? different color than Dataset? Was this previously discussed for ComputationalTools?)
- UI changes to enable filtering for just ResourceCatalogs? Note: split this out to a separate issue if this is expected to involve more extensive work (eg back-end changes other than simple API queries, UI testing). If this was previously enabled for ComputationalTools (and the implementation had previously been user tested, feel free to proceed based on the previous implementation
- Display of additional ResourceCatalog-specific fields in the record view (eg - collectionSize). Note, collectionSize is a recommended (rather than required) field so it's possible this field will have no values for a record.

Next steps:
- [x] Generate Lyssna tests as needed to address above uncertainties (No need to do a G-doc write up for the test, just create a GH issue for it [using this template](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/new?assignees=&labels=ux&projects=&template=ux_test.yml&title=%5BUX+Test%5D%3A+). Assigned to @EmilyHaag as some of the aboved TBD content may already have been tested or just accepted by the NIAID team for ComputationalTools. If so, no need to retest.
- [x] @EmilyHaag @leandrocollares Conduct Lyssna test and analyze results
- [x] @candicecz Create mock ups based on results of Lyssna tests
- [x] @candicecz For easily reverted changes, move to staging. If changes are not easily reverted, @gtsueng to seek NIAID approval first before moving to staging
- [ ] @gtsueng Seek NIAID approval to move to production 

### Issue Discussion

This issue was discussed at the bi-weekly meeting dated 2024.01.30

### WCAG Compliance Check

- [ ] The ui changes are not expected to significantly affect WCAG compliance (ex- wording changes)
- [ ] The ui changes have visual elements which have yet to be tested for WCAG compliance
- [x] The ui changes have visual elements which have been tested for WCAG compliance
- [ ] The ui changes have passed all checks for WCAG compliance

### Related WBS task
- https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53
- https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11
- https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### UI change status check list

- [ ] This ui change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This ui change has been discussed/reported between NIAID, Scripps, Leidos
- [x] This ui change has been mocked up
- [ ] This ui change has been implemented on Dev
- [x] This ui change has been approved for Staging
- [ ] This ui change has been implemented on Staging
- [ ] This ui change has been approved for Production
- [ ] This ui change has been implemented on Production

**Comment by gtsueng** [comment]
The following feedback was provided on the Resource Catalog search results view in staging on 2024.03.05 during the ODSET in person meeting: 

> It's still unclear what the difference is between Resource Catalog and Dataset. Please provide a simple alt text definition to make it more clear.

**Comment by gtsueng** [comment]
Adding alt text to the 'Type' term on the filter can help the user to know to look there to filter for types.
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/8faf7584-c73c-4bb0-92f0-756f013da7e7)

In terms of a definition...
* Schema.org uses the following definition: "The schemas are a set of 'types', each associated with a set of properties. The types are arranged in a hierarchy." Which is rather uninformative for anyone unfamiliar with schemas.
* Bioschemas provides the following defintion: "Schema.org provides a way to add semantic markup to web pages. It describes ‘types’ of information, which then have ‘properties’. The types are things that we can talk about and the properties are the things that we can say about the type." Which is more informative, but too verbose

For the NIAID Data ecosystem, something short but succinct would be best. Maybe something like:
"The type of metadata record available in the NIAID Data Ecosystem"

**Comment by gtsueng** [comment]
Here's the definition of Type from Dublin Core: "Type is used to categorize the nature or genre of the content of the resource"... it's probably the briefest available definition available that makes sense.

**Comment by candicecz** [comment]
This type definition has been added to the [staging ](https://data-staging.niaid.nih.gov/search) and [production ](https://data.niaid.nih.gov/search) instance.

**Comment by gtsueng** [comment]
I am marking this issue as `Pending close out`. If there are no further comments on this issue within the week, it will be closed.
