### ISSUE TITLE
[User Interface: STRAPI-based Page]: Repository-level Metadata Compatibility Badge Documentation

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#228]
### Issue Name

Repository-level Metadata Compatibility Badge Documentation

### Issue Description

According to the NIAID team, a repository owner was excited about the Metadata Completeness badge, but lamented that it was not informative enough. This prompted the NIAID team to request improvements to the legend for the metadata completeness badge suggesting the inclusion of missing fields. Since missing fields can be repository-limited, it makes more sense for this sort of information to be provided at the repository level. Towards that end, we will create a repository-level metadata compatibility badge which will help visualize how compatible repositories are with the metadata ingested by the NIAID Data Ecosystem.

Similar to the documentation page for the Metadata completeness badges, a documentation page/explanation is needed for the Repository-level Metadata compatibility badge.

### Issue Discussion

The history of this ticket can be sourced to this issue: https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/5?pane=issue&itemId=50899235

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/19
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/45

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [X] In progress
- [ ] Blocked
- [ ] Will not address

### STRAPI page status check list

- [ ] This page/documentation/change has yet to be discussed between NIAID, Scripps, Leidos
- [X] This page/documentation/change has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This page/documentation/change has been mocked up
- [ ] This page/documentation/change has been implemented on Staging
- [ ] This page/documentation/change has been approved for Production
- [ ] This page/documentation/change has been implemented on Production

**Comment by gtsueng** [comment]
Per the ODSET onsite meeting dated 2024.03.06, for both this documentation page and the Metadata Completeness Badge Documentation: Make explicit that the score is not because the metadata isn’t there, but because it isn’t findable

**Comment by gtsueng** [comment]
Per discussions during the biweekly meeting dated 2024.06.11, the documentation should be updated to reflect a positional shift in the purpose of the repository-level metadata compatibility badge as well as changes in the design

See https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/227 for additional details

**Comment by EmilyHaag** [comment]
Documentation has been updated: https://docs.google.com/document/d/1Q1_S3x239slpAhMpOnNTJKLzdc9ik7Up4H6Dty-U7xs/edit?usp=sharing

**Comment by gtsueng** [comment]
@EmilyHaag the badge that the NIAID team is most interested in is the BarChart/GridPlot Hybrid (second badge from top): https://nde-dev.biothings.io/compatibility

Please add it to the documentation

**Comment by gtsueng** [comment]
@rshabman @hartwickma @lisa-mml @sudvenk,

The documentation has been updated to reflect the NIAID teams' preferred design for the metadata compatibility badge. The text has been updated to include the value of the badge to data contributors as well as cautionary language on interpreting the badge.

https://docs.google.com/document/d/1Q1_S3x239slpAhMpOnNTJKLzdc9ik7Up4H6Dty-U7xs/edit?usp=sharing

The Ask: We seek to add this documentation to Staging along with the metadata compatibility badge

**Comment by hartwickma** [comment]
Hi @gtsueng thank you providing a link to the updated documentation. The documentation should be updated to represent that this is repository compatability and remove references to individual datasets and percent coverage (and associated calculation text).

**Comment by gtsueng** [comment]
We have updated the documentation per the request. @EmilyHaag please add the draft documentation to staging for this issue.

**Comment by EmilyHaag** [comment]
This is on staging: https://data-staging.niaid.nih.gov/knowledge-center/metadata-compatibility-badge

**Comment by gtsueng** [comment]
@hartwickma @rshabman @lisa-mml @sudvenk

The documentation for the repository-level metadata completeness badge can now be viewed on Staging: https://data-staging.niaid.nih.gov/knowledge-center/metadata-compatibility-badge.

The Ask: We seek approval to push this documentation to Production along with the Repository-level metadata compatibility badge

**Comment by hartwickma** [comment]
Hi @gtsueng, thank you for this update. Unless there is substantial change or concern, please move towards production. NIAID does not need to review in between steps.

**Comment by gtsueng** [comment]
@hartwickma @rshabman @lisa-mml @sudvenk

This documentation page is now [on production](https://data.niaid.nih.gov/knowledge-center/metadata-compatibility-badge).

We are marking this issue as `pending close out` and will close it after a week if there are no new changes to be made.
