### ISSUE TITLE
[UX Test]: Topic Categories Test

### ISSUE THREAD

**Issue by leandrocollares** [NIAID-Data-Ecosystem/nde-portal#230]
### Issue Name

Topic Categories Test

### Test Purpose

To answer the following questions:

1. Which topic category design do users prefer?

1. What made users choose the said design?

### Test Approach

The test will be conducted with 25 participants on Lyssna.

Participants will be shown 4 dataset card designs featuring topic categories and asked to choose one design. Later, participants will be asked to provide reasons for their choices. 

### Test Cost

$75

### Test Time

The test is expected to take 2 days to set up, <1 day to collect results, and 1 day to analyze results.

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/53

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### Test status check list

- [ ] This test has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This test has been discussed/reported between NIAID, Scripps, Leidos
- [X] This test has been scoped out
- [X] This test has been drafted in the platform in which it will be conducted
- [ ] This test has been conducted
- [ ] The results of this test have been analyzed

**Comment by gtsueng** [comment]
As the NIAID team have already indicated their preference in the mock ups, I'm marking this issue as 'pending close out' and will close it after a week if there are no more comments/concerns
