### ISSUE TITLE
[UX Test]: Landing page table

### ISSUE THREAD

**Issue by candicecz** [NIAID-Data-Ecosystem/nde-portal#232]
### Issue Name

 Landing page table test

### Test Purpose

The test will be used to determine which table best displays repository data on the front-end.

The main areas of interest include:
- The layout of the filters.
- The layout of the table (number of columns, types of columns)
- The layout + color scheme of the tags

### Test Approach

The test will be conducted with 25 participants on Lyssna.

https://drive.google.com/file/d/12iY7BFPJTLN1xOYTAyILZ_aCalWieVok/view?usp=drive_link

### Test Cost

$75

### Test Time

The test is expected to take 2-3 days for set up. 1 day for data collection and 1 day for analysis.

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### Test status check list

- [ ] This test has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This test has been discussed/reported between NIAID, Scripps, Leidos
- [x] This test has been scoped out
- [x] This test has been drafted in the platform in which it will be conducted
- [x] This test has been conducted
- [x] The results of this test have been analyzed

**Comment by gtsueng** [comment]
Results added: https://drive.google.com/file/d/1ASKjbBEz9cow9QbSuRREqIgSO026q9wb/view

**Comment by gtsueng** [comment]
The test has been completed. We are marking this issue as `pending closeout` and will close it within a week if no further tests are needed. This ticket has been linked to the [appropriate issue](https://github.com/orgs/NIAID-Data-Ecosystem/projects/6/views/2?pane=issue&itemId=55861377) for ease of access.
