### ISSUE TITLE
Updating resource ID in the URL

### ISSUE THREAD

**Issue by candicecz** [NIAID-Data-Ecosystem/nde-portal#235]
Per our discussion on 4/24/2024, we decided that certain improvements can be made to the resource id in the API and it's handling in the front-end so as to follow best practices for URL naming conventions. This change also improves SEO search engines are not always handling URLS with case sensitivity.

Action items: 

- [x]  @DylanWelzel and @jal347 will make the `_id` field case-insensitive.
- [x] @DylanWelzel and @jal347 will ensure the `_id` is free of any non-url-safe characters.
- [x] @candicecz will update the routes from https://data.niaid.nih.gov/resources?id={id} to https://data.niaid.nih.gov/resources/{id}  and update the canonical url accordingly.

### Related WBS task
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/33

**Comment by gtsueng** [comment]
Note that the `DS_` in VEuPathDB identifiers appear to be case sensitive:
https://data.niaid.nih.gov/resources?id=veupathdb_DS_0273077ad5

In VEuPathDB: https://veupathdb.org/veupathdb/app/record/dataset/DS_0273077ad5

Will fail: https://veupathdb.org/veupathdb/app/record/dataset/ds_0273077ad5

**Comment by candicecz** [comment]
@gtsueng  We use the `url` field to direct the user to the dataset. So as long as we don’t transform the id in the `url` property, it should be ok.

**Comment by gtsueng** [comment]
We are marking this issue as `pending close out` and will close it after a week if no new comments or concerns arise
