### ISSUE TITLE
[UX Test]: Terminology test

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#236]
### Issue Name

Terminology test

### Test Purpose

To understand the interpretability of terms and identify the best term for use in the Discovery Portal.

Term set 1 (`resource` | `source` | `record`): Should a `ResourceCatalog` be consistently referenced as a `Resource` or `Source` throughout the site? Should a record be referenced as a `resource` or a `record` in the url?
* Currently, on production (no ResourceCatalog) we use `Source`, but in staging (ResourceCatalogs added) we use `Resource` on the landing page but `Source` on other parts of the site

Term set 2 (`Data Catalog` | `Dataset Repository` | `Dataset Catalog`): The schema.org term for the resources we've already ingested is `DataCatalog`, and this is the term used in NCBI's Dataset search page. However, the term Data Catalog may appear vague to users who are unfamiliar with Schema.org and may include sources that we are unable to ingest. The terms `Dataset Catalog` or `Dataset Repository` provides a little more distinction to help indicate that a resource is one that we can ingest.

Term set 3 (`open` | `open access`): When listing different conditions of access in a column with column header `Access`, does using the full term `open access` improve the interpretability relative to using the term `open` alone?

Term set 4 (`metadata completeness` | `metadata compatibility`): Some records will never be able to fully "complete" the metadata by nature of the record. For example, an allergy-specific dataset record may not necessarily have an `infectiousAgent` by nature and will therefore never be complete. How interpretable is the term `metadata completeness` relative to `metadata compatibility`? How are these terms interpreted

### Test Approach

TBD

### Test Cost

TBD

### Test Time

2-3 days for set up, 1 day for data collection

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/51

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [x] In progress
- [ ] Blocked
- [ ] Will not address

### Test status check list

- [X] This test has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This test has been discussed/reported between NIAID, Scripps, Leidos
- [x] This test has been scoped out
- [x] This test has been drafted in the platform in which it will be conducted
- [x] This test has been conducted
- [x] The results of this test have been analyzed

**Comment by EmilyHaag** [comment]
Test results can be found [here](https://docs.google.com/presentation/d/1fqEkJYOlrF9iVCxzr8h75eSqItlwQuzG/edit?usp=sharing&ouid=114065631315523104759&rtpof=true&sd=true)

**Comment by gtsueng** [comment]
The results posted by @EmilyHaag suggest that the following terminology should be used consistently throughout the site:
**Resource vs Source vs Record**
- Resource: should be used to reference a single record on the site (Dataset OR ResourceCatalog)
- Source: should be used to reference the data provider
- Record: do not use this term
Impact: URL structure for each record to remain using 'resource' (`https://data.niaid.nih.gov/resources?id=S-EPMC7818909`). Affects term use in redesign of landing page for including ResourceCatalogs
![image](https://github.com/NIAID-Data-Ecosystem/nde-portal/assets/9200138/c4a9a212-9fb3-49e0-a2e2-c94e71451ad1)

**Data Catalog vs Dataset Repository vs Dataset Catalog**
- The term Dataset Repository is the most readily interpreted term
Impact: Use of Dataset Repository is readily understood and should be used in the redesigned landing page even if other sites use terms like 'Data Catalog'

**open vs open access** 
- spelling out 'access' in the table did not significantly improve the user understanding
- Impact: Aside from using slightly more real estate in the landing page table, there is no harm in using the term 'open access' vs 'open' on its own. It may potentially be advantageous to use the term 'open access' as opposed to just open if a screen reader is used

**metadata completeness vs metadata compatibility**
- Users better understood the term metadata completeness for a record-level metadata completeness badge, than the term metadata compatibility for the same badge

**Comment by gtsueng** [comment]
This issue has been marked as `pending close out` and will be closed after a week if there are no additional concerns surrounding this issue

**Comment by gtsueng** [comment]
Per an email dated 2024.06.06 in an email requesting for more information on the study results, I am marking this issue as `review for info`

**Comment by hartwickma** [comment]
Hi @gtsueng, NIAID agrees to move forward with Resource, Dataset Repository, and Open, but would like retain Metadata Compatability as the preffered terminology (discussed in bi-weekly meeting). We may wish to revisit terminology at a later date.

**Comment by gtsueng** [comment]
@hartwickma @sudvenk thanks for the update! We will keep the terminology for the repository-level metadata compatibility badges as is.
