### ISSUE TITLE
[UX Test]: Home Page Design - Sources Table

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#243]
### Issue Name

Home Page Design - Sources Table

### Test Purpose

This test will determine the optimal design of the Sources table on the Home Page. Currently, the Home page on the production site is a simplified view with Name and Description, while the design on the staging site includes 3 additional columns. The test will determine if the 3 additional columns are an improvement on the original design, and if filtering becomes confusing if these columns are not included.

### Test Approach

The test will be conducted with 25 participants on the Lyssna platform. The test will also be sent to the GoFAIR US team.

### Test Cost

$75

### Test Time

The test is expected to take 1-2 days to set up, 1 day to collect results, and 1 day to analyze results.

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/51

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [X] In progress
- [ ] Blocked
- [ ] Will not address

### Test status check list

- [ ] This test has yet to be discussed between NIAID, Scripps, Leidos
- [X] This test has been discussed/reported between NIAID, Scripps, Leidos
- [X] This test has been scoped out
- [ ] This test has been drafted in the platform in which it will be conducted
- [ ] This test has been conducted
- [ ] The results of this test have been analyzed

**Comment by gtsueng** [comment]
The results of this study can be found here: https://docs.google.com/presentation/d/1HAFuqGolPBYW4ixcjTeRkOdqnRvIvu_o/edit?usp=sharing&ouid=114065631315523104759&rtpof=true&sd=true

**Comment by gtsueng** [comment]
Per an email dated 2024.06.06 in an email requesting for more information on the study results, I am marking this issue as `review for info`

**Comment by hartwickma** [comment]
Hi @gtsueng, NIAID agrees to proceed with current design but may wish to revisit this design at a later date.

**Comment by gtsueng** [comment]
As the study result have been reviewed, I am marking this issue as `pending close out` and will close this issue after a week if there are no further comments to be addressed.
