### ISSUE TITLE
[REQUESTS]: Improve the clarity of the `Not specified` and `Any specified` filter options

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#256]
### Issue Name

Improve the clarity of the `Not specified` and `Any specified` filter options

### Issue Description

OCGR found these filter options to be confusing for the 'Program Collections' filter. To clarify these filter options, OCGR suggested the addition alt-text to explain that `Not specified` = "{filter name} not specified, missing, or unavailable" and that `Any specified` = "One or more {filter name(s)} is specified, found, or available"

NIAID suggested the alternative of integrating the filter name with the filter option. 
For example: "{filter name} not specified" or "Any {filter name}"; however, given the length of some of the filter names, (e.g. - Health Condition, Program Collection), this could be excessively long as a filter option (e.g. "Program collection not specified" is quite lengthy. As a result, we have decided to implement the OCGR suggestion as a logical first step. If this option does not suffice, we can investigate additional options.

### Issue Discussion

This issue was raised by OCGR at the bi-weekly meeting dated 2024.09.03

### Request Type

Other

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### Request status check list

- [X] The request has been scoped
- [X] Some immediate discussion or action on the matter was started, but additional information needed
- [X] One or more new GitHub Issues, Pull Requests, or files in Google Drive have been created to address the request
- [x] The request is awaiting approval to move to staging
- [x] The request is awaiting approval to move to production
- [ ] The request is awaiting approval for closeout
- [ ] The request has been addressed and closeout of the issue is approved

**Comment by candicecz** [comment]
Tooltips for added clarity are now on the [staging instance](https://data-staging.niaid.nih.gov/search).

![image](https://github.com/user-attachments/assets/41c306cf-b068-45a1-af34-1406900f4fe4)
![image](https://github.com/user-attachments/assets/260793bc-b3d0-4abe-b941-f1713ad9d82e)

**Comment by gtsueng** [comment]
This is considered a technical issue on par with https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/209

NIAID does not need to approve of issues at this level. Please move this to Production.

**Comment by candicecz** [comment]
@ginger this change is live on [production](https://data.niaid.nih.gov/search)

**Comment by gtsueng** [comment]
Thanks! I am marking this issue as `pending close out` and will close it after a week if no new changes are needed

**Comment by candicecz** [comment]
Added analytics tracking to further inform use of the "any" and "not" specified filter options
