### ISSUE TITLE
[REQUESTS]: update knowledge center to match new color scheme on landing page

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-portal#258]
### Issue Name

update knowledge center to match new color scheme on landing page

### Issue Description

The updated color scheme is now available on production, but the old color scheme remains for the documentation (knowledge center). Update the color scheme for the knowledge center

https://data.niaid.nih.gov/knowledge-center

### Issue Discussion

This was mentioned by OCGR at the biweekly meeting dated 2024.09.03

### Request Type

Other

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### Request status check list

- [X] The request has been scoped
- [ ] Some immediate discussion or action on the matter was started, but additional information needed
- [ ] One or more new GitHub Issues, Pull Requests, or files in Google Drive have been created to address the request
- [ ] The request is awaiting approval to move to staging
- [ ] The request is awaiting approval to move to production
- [ ] The request is awaiting approval for closeout
- [ ] The request has been addressed and closeout of the issue is approved

**Comment by candicecz** [comment]
Knowledge center banner has been updated with the same color scheme on the [staging instance.](https://data-staging.niaid.nih.gov/knowledge-center)

**Comment by gtsueng** [comment]
@candicecz go ahead and move to prod -- this is such a minor change and it was OCGR that proposed it, so I don't think it's necessary to seek approval for it.

**Comment by candicecz** [comment]
Now live on the [production instance](https://data.niaid.nih.gov/knowledge-center)

**Comment by gtsueng** [comment]
@hartwickma, @lisa-mml, @rshabman, @sudvenk

The quick-fix suggestion from OCGR to match the color scheme of the knowledge center to the landing page has been implemented on production.

This issue has been marked as `pending close out` and will be closed in a week if no additional changes are needed.
