### ISSUE TITLE
allow "OR" in faceting

### ISSUE THREAD

**Issue by andrewsu** [NIAID-Data-Ecosystem/nde-portal#30]
When I execute the test search for Ebola https://nde-portal.vercel.app/search/?q=%22Ebola%22%20OR%20%22EBOV%22%20OR%20%22EVD%22, I see this:

![image](https://user-images.githubusercontent.com/2635409/164300544-72dcfe62-56a1-42ac-9327-ddcbb5d7f35d.png)

I see 13 `CreativeWork`s and 6 `Chapter`s, but currently it's not possible to adjust the facets to see the 19 records that correspond to union of those two types.  I get why the counts update based on the currently-applied facets, but somehow I think the options for the same facet category (e.g., `Type` in the example above) should be handled differently than for other facet categories (e.g., `Source`, or `Keywords`).  Perhaps Amazon (or similar) can provide a guide for the desired behavior?

**Comment by flaneuse** [comment]
I think that's a bug-- I think the goal was to have within each facet for the terms to be OR'd but between facet types, they would be AND'd (like `@type: CreativeWork OR Chapter AND measurementTechnique: RNASeq`)
