### ISSUE TITLE
Fix routing based on `/portal`

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#32]
@candicecz : it looks like the links within the portal all route to `/staging` instead of `/portal`.

To reproduce:
* from https://data-staging.niaid.nih.gov/portal, clicking on E. coli routes to a [/staging/search]((https://data-staging.niaid.nih.gov/staging/search/?q=%22E.coli%22+OR+%22Escherichia+coli%22+OR+%22Shiga+Toxin-Producing+E.coli%22+OR+%22STEC%22) page.
* Clicking refresh on the page leads to an nginx/404 error. 

We might need to adjust the ngnix server-side routing-- let us know if that's the case.

**Comment by candicecz** [comment]
I fixed the links to switch to /portal and everything seems ok except the refresh issue that you mentioned.
 @newgene, any ideas on how to fix this?
![image](https://user-images.githubusercontent.com/25373313/166268021-5f00a3fe-b6af-48bb-846d-c72ab1183b8b.png)

**Comment by newgene** [comment]
@candicecz looks like the routing configuration for `/portal` adds an extra `/`: `staging//about` instead of `staging/about`. We should ask SB to remove the trailing `/` from the routing settings.
