### ISSUE TITLE
[bug] edge cases on summary page lead to broken page

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#53]
Certain searches / search + filter combos lead to an error that breaks the page:

<img width="634" alt="Screen Shot 2022-06-27 at 11 39 24 AM" src="https://user-images.githubusercontent.com/8041065/176012496-3f460d00-c3b7-41cd-aa63-9765d0033927.png">

Looks like maybe it's an empty array / null value causing problems?

Example bad queries found:

- https://data-staging.niaid.nih.gov/portal/summary/?q=Asthma
- https://data-staging.niaid.nih.gov/portal/summary/?q=funding.identifier%3A%28%22U01AI124255%22+OR+%22AI124255%22+OR+%22U01AI124275%22+OR+%22AI124275%22+OR+%22U01AI124290%22+OR+%22AI124290%22+OR+%22U01AI124302%22+OR+%22AI124302%22+OR+%22U01AI124316%22+OR+%22AI124316%22+OR+%22U19AI135972%22+OR+%22AI135972%22+OR+%22U19AI135976%22+OR+%22AI135976%22+OR+%22U19AI135990%22+OR+%22AI135990%22+OR+%22U19AI135995%22+OR+%22AI135995%22+OR+%22U19AI135964%22+OR+%22AI135964%22+OR+%22U01+AI124319%22+OR+%22U01AI111598%22+OR+%22U19+AI106761%22+OR+%22U19AI106754%22+OR+%22U19AI106772%22+OR+%22HHSN272201200031C%22%29&from=1&filters=infectiousAgent.name%3A%28%22Staphylococcus+aureus%22%29
- https://data-staging.niaid.nih.gov/portal/summary/?q=funding.identifier%3A%28%22U01AI124255%22+OR+%22AI124255%22+OR+%22U01AI124275%22+OR+%22AI124275%22+OR+%22U01AI124290%22+OR+%22AI124290%22+OR+%22U01AI124302%22+OR+%22AI124302%22+OR+%22U01AI124316%22+OR+%22AI124316%22+OR+%22U19AI135972%22+OR+%22AI135972%22+OR+%22U19AI135976%22+OR+%22AI135976%22+OR+%22U19AI135990%22+OR+%22AI135990%22+OR+%22U19AI135995%22+OR+%22AI135995%22+OR+%22U19AI135964%22+OR+%22AI135964%22+OR+%22U01+AI124319%22+OR+%22U01AI111598%22+OR+%22U19+AI106761%22+OR+%22U19AI106754%22+OR+%22U19AI106772%22+OR+%22HHSN272201200031C%22%29&from=1&filters=includedInDataCatalog.name%3A%28%22Data+Discovery+Engine%22%29
- https://data-staging.niaid.nih.gov/portal/summary/?q=%22Influenza%22+OR+%22Flu%22&from=1&filters=funding.funder.name%3A%28%22NIH+HHS%22%29

**Comment by DylanWelzel** [comment]
In Summary Table:
`Math.ceil(size < MAX_RESULTS ? total : MAX_RESULTS) / size` changed to `Math.ceil((size < MAX_RESULTS ? total : MAX_RESULTS) / size)` to guarantee integer
