### ISSUE TITLE
[bug] Searching ACTT doesn't give the expected results

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#58]
[Searching "ACTT"](https://data-staging.niaid.nih.gov/portal/search/?q=actt&from=1) only returns one result, when there should be [4 results](https://data-staging.niaid.nih.gov/portal/search/?q=Adaptive+COVID-19+Treatment+Trial&from=1&filters=includedInDataCatalog.name%3A%28%22AccessClinicalData%40NIAID%22%29)

@jal347 : this is my fault, isn't it?  since I didn't split on hyphens?  trying to figure out how to get the best of both worlds...

**Comment by flaneuse** [comment]
proposal from @newgene : modify the Query on the backend to auto-add a `*` wildcard to all queries EXCEPT quoted queries.

**Comment by jal347** [comment]
@flaneuse I fixed the api behavior accordingly but there might be some problems b/c the way @candicecz queries our api, i have to strip the beginning and end parenthesis. If the user meant to include parenthesis in the query then they wont get the result they want.
