### ISSUE TITLE
Rethink the behavior of the search results expansion panel

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#61]
Potential disconnect in expected behavior for the search results expansion panel.  While the icons were clear on what was available/not, the user expected clicking on "funding" would show only the funding info, not the expand the "more details" panel.

Propose waiting for more user feedback on the expected behavior.

**Comment by candicecz** [comment]
Related to #78

**Comment by candicecz** [comment]
Related to #200

**Comment by candicecz** [comment]
Cards metadata re-design is viewable on staging: https://data-staging.niaid.nih.gov/search

**Comment by candicecz** [comment]
Card metadata re-design is viewable on production: https://data.niaid.nih.gov/search?q=%22Asthma%22
