### ISSUE TITLE
[enhancement] Add missing metadata as a filter option?

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#62]
User found it confusing that `healthCondition`, for instance, only had a few hundred entries for a query which had thousands of results. Since the "missing" entries come from datasets/tools which lack that metadata, might be good to add an entry for "n/a" or similar in the filters:

<img width="1191" alt="Screen Shot 2022-07-19 at 2 04 42 PM" src="https://user-images.githubusercontent.com/8041065/179848348-d8175e83-1816-44ee-8ec8-87f4ed548f29.png">

**Comment by gtsueng** [comment]
In the longer term, you can also try using [PubTator](https://www.ncbi.nlm.nih.gov/research/pubtator/api.html) to pull disease MeSH IDs out of the text. If the datasets have pubmed or PMC citations, those have been preprocessed by PubTator, so you can just download them, then use Wikidata or some other x-ref to convert to MONDO for this field.

**Comment by flaneuse** [comment]
Datasets which do not have healthCondition: https://api.data.niaid.nih.gov/v1/query?q=-_exists_:healthCondition

**Comment by EmilyHaag** [comment]
NIAID commented on the number of missing fields: "Concerned that there is a lot of empty data for many fields. For example, I searched with glioma and the Best Match is “Ferroptosis-Related Gene Signature Predicts Glioma Cell Death and Glioma Patient Progression” but the Health Condition field is blank…it should be Glioma. Species field is blank and should be Human. Having such huge and obvious gaps does not present well…so if the data is not available and is not easily extracted then those fields are not shown to users."
