### ISSUE TITLE
[documentation] Clarify the difference between a data license and data usage agreement 

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#63]
DUA is missing for AccessClinicalTrials datasets; potentially rename "license" to "license or data usage agreement"

**Comment by flaneuse** [comment]
Additional concerns that calling a DUA a "license" may imply a relationship with intellectual property.  Might want to specify as a separate property, or tag it as a type of `license`?

**Comment by flaneuse** [comment]
@gtsueng recommends separating these into `license` and `usageInfo`

**Comment by gtsueng** [comment]
You can encode the DUA object as `@type`:`CreativeWork` and include the property `additionalType` : `https://sharing.nih.gov/data-management-and-sharing-policy/sharing-scientific-data/data-sharing-approaches#data-use-agreement`.
