### ISSUE TITLE
Flatten .csv download of metadata

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#65]
Right now, the metadata download in .csv format is cumbersome to use, since nested objects are embedded in a cell. ideally, each object's key will be a different column.  Also need to figure out how to deal with arrays of objects; a long list makes sense, BUT then you'd have to repeat rows, which might get confusing.

Propose categorizing this as a low priority for the moment, since it's a high level of effort v. the expected usage.

**Comment by flaneuse** [comment]
from @newgene : add parameter `&dotfield=true` to traverse nested objects: https://api.data.niaid.nih.gov/v1/query?dotfield=true. Won't solve array issues.

**Comment by gtsueng** [comment]
If python, pandas explode function works wonders for arrays nested in dataframes
