### ISSUE TITLE
Filtering counts not matching results

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#80]
One user tried the following workflow:
- Search for "TB"
- Filter on "Health Condition"
- Click "**Tuberculosis (13)**", but only **6 results** appear
- (They also want "Tuberculosis" and "tuberculosis" grouped into 1. [See ticket](https://github.com/NIAID-Data-Ecosystem/nde-portal/issues/81))

They also mentioned this workflow as a bug, but I was **not able to replicate**. (This feedback was collected on 8/22/2022 8:11:18)
- Search for "ACTT"
- Filter on "Source"
- Click "AccessClinicalData (4)", but only 2 results appear

**Comment by candicecz** [comment]
This is an ongoing issue with the API filters - should be fixed soon.
