### ISSUE TITLE
Standardize metadata used by filters for differences in capitalization

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#81]
Feedback collected during Phase 0 testing: "Standardize metadata capitalization, e.g., Tuberculosis and tuberculosis are presented as 2 health conditions"

**Comment by flaneuse** [comment]
Addressing in two ways:
1. Adding lowercase normalization within the Elasticsearch mapping, so those two values are handled the same
2. Longterm: @DylanWelzel standardizing values for `infectiousAgent`, `species`, `healthCondition`, etc.
