### ISSUE TITLE
Shorten metadata description tooltips

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#82]
Feedback collected during Phase 0 testing: "Tooltips for the metadata icons on main page are too cryptic and long, default to one quick sentence, then link to more for full definition on a definitions page?"

**Comment by candicecz** [comment]
I think we should have some more robust definitions shortly. So I'll wait for those to be added before addressing this issue.

**Comment by EmilyHaag** [comment]
If you mouse over the "i" icon, you get both the description and the name of the metadata field. Can we remove the second one that's just the field name?
![Picture1](https://user-images.githubusercontent.com/75391907/188782053-f7c5ba71-541d-4025-aa95-acf39af15c5e.png)

**Comment by candicecz** [comment]
> If you mouse over the "i" icon, you get both the description and the name of the metadata field. Can we remove the second one that's just the field name? ![Picture1](https://user-images.githubusercontent.com/75391907/188782053-f7c5ba71-541d-4025-aa95-acf39af15c5e.png)

Fixed.
