### ISSUE TITLE
Add button to browse all

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#85]
NIAID suggested a browse feature, noting that an empty search is essentially the same, but a browse button would be a good addition

**Comment by flaneuse** [comment]
I think there's also opportunities to think (down the line) about doing something like browsing by category (see "data type" suggestion #83 ), by health condition, infectious disease, measurement technique, etc. -- and also potentially visualizing the breakdown of datasets/tools by those 

however:
1. this will probably require a good bit of metadata cleanup/standardization (see #81 etc.)
2. i'm really wary of creating the standard view of many repos / portals, which are just an array of donut charts with very tiny slices by each dimension.  Will have to think about what to show in a "browse" view that would make it most useful
