### ISSUE TITLE
Embed structured metadata into the html for the Dataset/Tool pages

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#9]
On all the [individual dataset pages](https://nde-portal.vercel.app/resources/ZENODO_807548), need to embed the structured metadata so the pages are crawlable by Google Dataset Search.

[Instructions from Google](https://developers.google.com/search/docs/advanced/structured-data/dataset)

Or basically:
1. add `<script type="application/ld+json"> {metadata}</script>` tag dynamically into the `<head>` of each page
2. Test in [Rich Results Test](https://search.google.com/test/rich-results)

**Comment by candicecz** [comment]
@flaneuse  I tested it and I think it's good though there are warnings about missing data fields. Could you double check also using [Rich Results Test](https://search.google.com/test/rich-results)? Thanks!
