### ISSUE TITLE
Filtering by date

### ISSUE THREAD

**Issue by EmilyHaag** [NIAID-Data-Ecosystem/nde-portal#96]
A Phase 1 user would like the results to be automatically filtered when inputting a date, instead of checking a box next to available dates using the current date filter. Manual date entry or the ability to select a date range may be more useful.

User feedback: "In the date filter tab when you input a year. It only filters out the available dates in the filter tab but not any of the actual data on the right panel. If you want data to be filtered and show up you have to click on the boxes next to each individual dates."

**Comment by flaneuse** [comment]
:tu: @candicecz @EmilyHaag seems like a range filter would be more useful -- "find me stuff after 2020", "find things between 2019-06-01 and 2019-09-30", etc.
